// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockProjectService.Infrastructure.DataContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MockProjectService.Infrastructure.Migrations
{
    [DbContext(typeof(MockProjectServiceDataContext))]
    partial class MockProjectServiceDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MockProjectService.Domain.Entities.MockProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseProjectUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MockProjects");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseClassCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MockProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepGuiding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MockProjectId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FinalAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("FinalGrade")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MockProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MockProjectId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.SubmissionsClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Grade")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionsClasses");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.Process", b =>
                {
                    b.HasOne("MockProjectService.Domain.Entities.MockProject", "MockProject")
                        .WithMany("Processes")
                        .HasForeignKey("MockProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockProject");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.Submission", b =>
                {
                    b.HasOne("MockProjectService.Domain.Entities.MockProject", "MockProject")
                        .WithMany("Submissions")
                        .HasForeignKey("MockProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockProject");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.SubmissionsClass", b =>
                {
                    b.HasOne("MockProjectService.Domain.Entities.Process", "Process")
                        .WithMany("SubmissionsClasses")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockProjectService.Domain.Entities.Submission", "Submission")
                        .WithMany("SubmissionsClasses")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.MockProject", b =>
                {
                    b.Navigation("Processes");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.Process", b =>
                {
                    b.Navigation("SubmissionsClasses");
                });

            modelBuilder.Entity("MockProjectService.Domain.Entities.Submission", b =>
                {
                    b.Navigation("SubmissionsClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
